# permissions for end users to view filesets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: package-r-kubebuilder
    app.kubernetes.io/managed-by: kustomize
  name: fileset-viewer-role
rules:
- apiGroups:
  - package.r
  resources:
  - filesets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - package.r
  resources:
  - filesets/status
  verbs:
  - get
