# permissions for end users to edit objectsets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: package-r-kubebuilder
    app.kubernetes.io/managed-by: kustomize
  name: objectset-editor-role
rules:
- apiGroups:
  - package.r.package.r
  resources:
  - objectsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - package.r.package.r
  resources:
  - objectsets/status
  verbs:
  - get
