---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - package.r
  resources:
  - filesets
  - sources
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - package.r
  resources:
  - filesets/finalizers
  - sources/finalizers
  verbs:
  - update
- apiGroups:
  - package.r
  resources:
  - filesets/status
  - sources/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - package.r.package.r
  resources:
  - objectsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - package.r.package.r
  resources:
  - objectsets/finalizers
  verbs:
  - update
- apiGroups:
  - package.r.package.r
  resources:
  - objectsets/status
  verbs:
  - get
  - patch
  - update
